language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "nightly"  # nightly build
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script: pytest test_Parser.py
virtualenv:
  system_site_packages: true
env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6
